name = "ConnectionPool"
uuid = "eca4fab3-589c-4882-9470-d67ef7407f37"
authors = ["AbrJA <ajaimes@occ.com.mx> and contributors"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
